### ISSUE TITLE
haproxy30z 3.0.5-1.el9.zenetys vs rocky appstream haproxy 2.4 compile options and features

### ISSUE THREAD

**Issue by zam6ak** [zenetys/rpm-haproxy#10]
Hi
First of all thank you for providing RPM packages for newer releases of HAProxy!

We are running Rocky Linux v9.4 and are considering upgrading HAProxy to v3 using ZENETYS package.
Currently we are running v2.4.32 that comes from "AppStream" repository included with Rocky distribution.

However, if I compare the output of `haproxy -vv`  (see attached) between `3.0.5-1.el9.zenetys` and `2.4.22-3.el9_3`  from AppStream, I notice a lot of differences....

With `3.0.5-1.el9.zenetys`:
* Compiler used is older than Rocky's package
* Compile flags are different
* List of features is different (for example, Zenetys uses ZLIB and PCRE while Rocky uses SLZ and PCRE2)

Additionally if you compare v3 output from HAProxy official container on DockerHub, it is using newer OpenSSL version with HAProxy v3, while Zenetys package is using same version as HAProxy 2.4 on Rocky. Although I suspect this is because you just rely on what Rocky provides in order not to have more dependencies (like having to also provide and install newer OpenSSL).

I am not an expert on HAProxy compile options and features, but am hesitant to upgrade due to all the differences.
Any plans to release RPM package of v3 that would perhaps more closely match Rocky's?

Thanks
Z

[haproxy-vv-3.0.5-zenetys.txt](https://github.com/user-attachments/files/17446620/haproxy-vv-3.0.5-zenetys.txt)
[haproxy-vv-2.4.12-rocky9.txt](https://github.com/user-attachments/files/17446621/haproxy-vv-2.4.12-rocky9.txt)

**Comment by zam6ak** [comment]
After additionally comparing Docker images (both based on bookworm and alpine distros), feature lists seem to have same differences
They both have `+PCRE2 +PCRE2_JIT +SLZ`  instead of `zlib` and `pcre`..

**Comment by julthomas** [comment]
Hello @zam6ak,

> Compiler used is older than Rocky's package

I believe it is because the base el9 (rocky) image cached on our build host was created at a time gcc was gcc-11.2.1-9.4.el9.x86_64. I'll have a look, it is no problem to rebuild the image or better to add an update step.

> Compile flags are different

Will have a look, though the spec has %{optflags} and %{__global_ldflags} so I must dig into it.

> List of features is different (for example, Zenetys uses ZLIB and PCRE while Rocky uses SLZ and PCRE2)

SLZ, yes I saw that recently working on the quic package we plan to link with aws-lc. In that branch I started working on, I switched from ZLIB to SLZ, will do it as well in master (haproxy30z).

As for PCRE, I will dig in as well and test USE_PCRE2=1 USE_PCRE2_JIT=1

> OpenSSL [...] Although I suspect this is because you just rely on what Rocky provides in order not to have more dependencies [...]

Correct, "normal" packages (haproxy30z) are linked with standard distro libraries. There is sill a static link on an internal build of lua 5.4 but I want to remove it, it is historical from the el6, el7 times (el9 has lua 5.4 in standard).

I believe haproxytech docker images also use the openssl provided by the distro (https://github.com/haproxytech/haproxy-docker-debian/blob/main/3.0/Dockerfile, https://github.com/haproxytech/haproxy-docker-alpine/blob/main/3.0/Dockerfile), though they build with USE_QUIC_OPENSSL_COMPAT=1.

We have a haproxy30z+quic package that is not linked with the system's openssl but so far it is using quictls openssl 1.1.1w, which is not maintained anymore and for which I am planning to move to aws-lc. This may be interesting if you do not know that page https://github.com/haproxy/wiki/wiki/SSL-Libraries-Support-Status.

Julien

**Comment by zam6ak** [comment]
@julthomas  thank you for your prompt reply!

Using the same OpenSSL version as what distro provides makes sense as its not introducing another dep (at least for "normal" packages).
And making other changes would definitely make the package more in line with base offering (in terms of compiled features and options).

Do you perhaps have any timelines for when the next build with these changes would be available so we can better plan our upgrades?

Thanks
Z...

**Comment by julthomas** [comment]
Hello,
I have pushed haproxy30z-3.0.5-2 packages in our repos, you can read the details in each commit message.
Regarding the CFLAGS in haproxy -vv on haproxy 3.0, turns out it is "just" that warn/no-warn flags are not displayed anymore since some changes on the Makefile (see 141b319).
I switched to USE_SLZ=1 and USE_PCRE2=1, and switched back to linking with standard distro lua (shared).
Work will be done next on the quic package to switch to aws-lc.
Julien

**Comment by zam6ak** [comment]
@julthomas  thanks - this looks much closer (feature wise) with what is included with Rocky

I did another comparison of `3.0.5-2.el9.zenetys` with all the features compared with Rocky are same.
I did notice that  `3.0.5 docker-bookworm`, `3.0.5 docker-alpine`  have `+PCRE2_JIT` but since Rocky 2.4.22 does not have this turned on either it, that seems ok...


Again, thanks for your help
Z...
