### ISSUE TITLE
Does not support EL crypto-policies

### ISSUE THREAD

**Issue by nf-brentsaner** [zenetys/rpm-haproxy#4]
EL (RHEL, Alma, Rocky, etc.) have support for system-wide [crypto-policies](https://access.redhat.com/articles/3666211).

EL HAProxy supports this via e.g. `ssl-default-bind-ciphers PROFILE=SYSTEM`.

However, this does not seem to be recognized on your build.

**Comment by julthomas** [comment]
Hello @nf-brentsaner,

Sorry for the delay regarding this issue, I took some time today to dig into this.

I suppose you are using the quic branches because the classic build links with openssl from the distro.

As far as I understood it, RedHat patches openssl to support so called system-wide crypto-policy, so that PROFILE=SYSTEM is shortcut to the cipher list defined in /etc/crypto-policies/back-ends/openssl.config:

el8 patch, openssl branch 1.1.1:
https://git.rockylinux.org/staging/rpms/openssl/-/raw/r8/SOURCES/openssl-1.1.1-system-cipherlist.patch

el9 patch, openssl branch 3.0:
https://git.rockylinux.org/staging/rpms/openssl/-/raw/r9/SOURCES/0007-Add-support-for-PROFILE-SYSTEM-system-default-cipher.patch

This package's quic branches are static built againt quictls, fork of openssl that implements QUIC (https://github.com/quictls/openssl). So far we won't patch quictls, we want to keep it vanilla because we don't have time to adjust the patch so it applies, nor to do proper maintenance about it in case of problems.

Note that if we were to patch it, we would probably start from el8 patch because it is against openssl branch 1.1.1 which is the quictls branch used here at the moment. If you or anyone wants to help and has time to adjust the patch, we would consider including it.

That said, I realized that haproxy does not start with an ssl frontend using the default haproxy.cfg provided in our quic package because it references the PROFILE=SYSTEM cipher list. I will replace it with HIGH in the default config file.

Thanks for the report.

Julien

**Comment by nf-brentsaner** [comment]
Julien-

Thanks! We use config management so it wasn't a big deal for us to use an explicit cipher list if using your builds, but It does obviously cause issues in some cases if one isn't expecting it. :)

Crypto policies were introduced in EL 8.x; if you built against system OpenSSL there, should work fine in the future. I was under the impression EL 8.x's OpenSSL supported QUIC but perhaps not.
