### ISSUE TITLE
Add aarch64 support

### ISSUE THREAD

**Issue by chdeliens** [zenetys/rpm-haproxy#9]
Hi! Thanks for maintaining a RHEL repository for haproxy :) 
Is adding support/builds for the `aarch64` architecture possible?
That'd be much appreciated, as I'm always installing new packages on a local Rocky Linux 9 VM on my Macbook Pro M3 before creating Salt formulas, etc. to be deployed on our clusters.

Happy to help and discuss this further. thanks!

**Comment by julthomas** [comment]
Hello @chdeliens,
We won't be building for aarch64 in our repos because we have no time and resources to do it properly, sorry.
However you should be able to easily build the RPM yourself, provided you have a docker and bash on your system.
I tested from a rocky linux 9 aarch64 and got the RPM built with the following commands:
```
git clone https://github.com/zenetys/rpm-haproxy.git
cd rpm-haproxy/
dnf install podman-docker
./rpmbuild-docker -d el9
```
Julien
